
export const actionTypes = {

  LOGIN_SUBMITTING: "LOGIN_SUBMITTING",
  LOGIN_SUCCESS   : 'LOGIN_SUCCESS',
  LOGIN_FAIL      : 'LOGIN_FAIL',
    
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAIL   : 'LOGOUT_FAIL',

  DASHBOARD_LOADING: "DASHBOARD_LOADING",
  DASHBOARD_SUCCESS: "DASHBOARD_SUCCESS",
  DASHBOARD_FAIL   : "DASHBOARD_FAIL",


  REGISTER_USER_SUBMITTING: "REGISTER_USER_SUBMITTING",
  REGISTER_USER_SUCCESS   : "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAIL      : "REGISTER_USER_FAIL",
  
  GET_USERS_LIST_LOADING: "GET_USERS_LIST_LOADING",
  GET_USERS_LIST_SUCCESS: "GET_USERS_LIST_SUCCESS",
  GET_USERS_LIST_FAIL   : "GET_USERS_LIST_FAIL",

  
};
